# Generated by Django 4.2.16 on 2025-05-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houmanager', '0002_alter_bundles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundles',
            options={'managed': True},
        ),
    ]
