# Generated by Django 4.2.16 on 2025-05-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BundlesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'bundles_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BundlesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bundles_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BundleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'bundle_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'contexts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bundles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.IntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('frame_start', models.BigIntegerField(blank=True, null=True)),
                ('frame_end', models.BigIntegerField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('bundle_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houmanager.bundleslist')),
                ('bundle_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houmanager.bundletypes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='houmanager.categories')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='houmanager.contexts')),
                ('houdini_version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houmanager.versions')),
                ('tag', models.ManyToManyField(through='houmanager.BundlesTag', to='houmanager.tags')),
            ],
            options={
                'db_table': 'bundles',
                'managed': True,
            },
        ),
    ]
