# Generated by Django 4.2.16 on 2025-05-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundles',
            options={'managed': False},
        ),
    ]
